### PR TITLE
Add Job DSL support <DO NOT MERGE>

### PR DESCRIPTION
**Pull request by crummel**
- add azureStorageDownload and azureStorageUpload to Job DSL.
- depends on the pull request for managing artifacts: https://github.com/jenkinsci/windows-azure-storage-plugin/pull/23

### CODE REVIEW

**Comment by arroyc** [comment]
@crummel  #28 is the latest which cleans up #23, can you please update your code if needed?

**Comment by leitu** [comment]
will anyone still work with job dsl?

**Comment by gavinfish** [comment]
Closing outdated PR.

**Pull request closed without merging**
