### PR TITLE
PR-28 update

### PR DESCRIPTION
**Pull request by clguimanMSFT**
* Rebased [PR-28](https://github.com/jenkinsci/windows-azure-storage-plugin/pull/28)
* Changed the UI for donwloading an artifact so the user had to provide only the needed information and keep it backward compatible

### CODE REVIEW

**Comment by clguimanMSFT** [comment]
@roguishmountain please have a look

**Comment by clguimanMSFT** [comment]
The container is the default download type option:
image
And the project is the other exclusive option:

image

**Comment by roguishmountain** [comment]
@clguimanMSFT I made changes to the help files based on my change for backwards compatibility. These help files (help-builderContainerName.html and src/main/webapp/help-builderProjectName.html) should be updated.

**Comment by clguimanMSFT** [comment]
@roguishmountain those files are already updated. do you want to add text to them? If so please add the text here or commit in your old branch and I'll pick it up

**Comment by clguimanMSFT** [comment]
@arroyc please approve

**Comment by arroyc** [comment]
Done !!

**Pull request merged**
