### PR TITLE
Content type setting for published files

### PR DESCRIPTION
**Pull request by patope**
Adds 'content type' setting for uploaded files.
- Adds and fixes param attributes on javadocs (a newer jenkins build is more strict here)
- update azure-storage api to 1.1.0

### CODE REVIEW

**Comment by arroyc** [comment]
@patope  Can you please explain what is the user experience here and why do we want to store different content-type?

**Comment by patope** [comment]
@arroyc If i want use azure storage to distribute resources likes css or javascript, content type must be set correctly on those resources. Browsers wont accept css file as css file if content type is application/octet-stream. Azure CDN delegates content type from storage..

**Comment by ArielZhang** [comment]
I have the same problem, when can we merge the PR ?

**Comment by arroyc** [comment]
@ArielZhang  ... we are looking into it ... there are few priority PR's that we need to finish before .. will keep you posted .. in the mean time 0.3.3 is released today .. please try it and provide feedback .. thank you ...

**Comment by ArchangelSDY** [comment]
I'm closing this as it's implemented in #53 .

**Pull request closed without merging**
