### PR TITLE
3 small patches

### PR DESCRIPTION
**Pull request by smarie**
- Improved error messages, 
- Support for OS-based HTTP Proxy settings,
- Better '::folder' syntax behaviour allowing to merge several folders in one at the destination.

### CODE REVIEW

**Comment by arroyc** [comment]
@smarie , can you please explain the use case/user experience of this feature that you are trying to add?

**Comment by smarie** [comment]
@arroyc Wow this was a long time ago :)
One issue was that the plugin simply was not working in our network, because we are located behind a proxy. Just being able to confirm that was not easy because of the lack of debug error messages, so that's why I added more verbosity first.
Then there are several ways to support HTTP proxies in jenkins, none of them is perfect (or at least at the time :) ) so I thought that the easiest way to go was to simply make the plugin compliant with the standard proxy environment variables used everywhere (HTTP_PROXY, HTTPS_PROXY, and NO_PROXY).

The second issue was something with the plugin's "::folder" syntax that made us unable to merge several folders in one. Please check in the code for that one, that's far too long ago for me to remember. It was a quite straightforward and simple mod, though (a few lines).

Thanks very much for taking the time to integrate our feedback.

**Comment by arroyc** [comment]
@smarie , thanks for the details, we are new team and took it over recently, we are now going through old PRS and we will add them as per feature planning ... thank you for your feedback and contribution .. feel free to do the same  ...

**Comment by gavinfish** [comment]
Hi @smarie , this was a long long time ago :joy:

I am sorry to tell you that I have to close this PR because:

1. This PR was created a long time ago, and there has been some block changes for your changed files.
2. For the proxy issue, I have made a new PR #107 based on Jenkins own proxy setting.

Thanks for your contribution again. You are welcome if you have any questions or suggestions.

**Pull request closed without merging**
